### ISSUE TITLE
Consolidate YNAB converter scripts into just one?

### ISSUE THREAD

**Issue by torbengb** [trekdemo/bank2ynab.rb#1]
Hello Gergő!
I've noticed that there are nearly 90 GitHub projects related to YNAB converter scripts. In an effort to consolidate all (most) of these into a single tool, we've created `bank2ynab` as a flexible solution. [Have a look](https://github.com/torbengb/bank2ynab) if you're curious. 

It would be wonderful if you would share your bank's format with us? 
I would sincerely appreciate your valuable input. Thank you very much in advance!

You could either use [this form](https://goo.gl/forms/b7SNwTxmQFfnXlMf2) where we collect all our formats, or respond here in this issue (something like `"date";"account";payee";...`). We are making all the collected formats public so you can [grab a copy](https://docs.google.com/spreadsheets/d/1KmDkLWEx-aVMlUWpNXafovt6B9GbeDDZ2OruaOp_aqE/edit?usp=sharing) if you like.

Regards from Vienna,
Ben

**Comment by trekdemo** [comment]
Sorry @torbengb but I'm not using BudapestBank (HU) anymore, so I'm not sure if this project is still working.
